version: '2'
services:
  web:
    image: php:7.2-apache
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html
 
    #links: mysql #for mysql container - "db:db"     
    #sudo docker-compose exec mysql -u pac -p root1 pac < /home/straengel/projects/pac.sql
    #sudo docker-compose exec mysql --host=127.0.0.1 --port=3306 -u pac -p root1 pac < /home/straengel/projects/pac.sql
